name: Deploy Example App to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Usar pacote publicado no example-app
        run: |
          node ../scripts/switch-dep.cjs
        working-directory: ./example-app

      - name: Install example-app dependencies
        run: npm install
        working-directory: ./example-app

      - name: Build example-app
        run: npm run build
        working-directory: ./example-app

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        working-directory: ./example-app

      - name: Link Netlify site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
        working-directory: ./example-app

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=./dist --prod
        working-directory: ./example-app